services:
  # Backend
  - type: web
    name: shridhar-backend
    runtime: python
    buildCommand: "./backend_build.sh"
    startCommand: "cd backend && gunicorn shridhar_enterprise.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: shridhar_enterprise.settings
      - key: SECRET_KEY
        fromContext: secret
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      # Supabase DB
      - key: DB_ENGINE
        value: django.contrib.gis.db.backends.postgis
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        fromContext: secret
      - key: DB_HOST
        value: db.sqgghadcjrpfwttyfegi.supabase.co
      - key: DB_PORT
        value: "5432"
      # Email
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        value: gcp.shridharenterprise@gmail.com
      - key: EMAIL_HOST_PASSWORD
        fromContext: secret
      # External APIs
      - key: GCP_MAPS_PLATFORM_API
        value: AIzaSyBcwLjSEIpuh5mZfdoI8pqTRSc5Ztyfi1Q
      - key: PAYPAL_CLIENT_ID
        value: AQBH1f4jL1K6_fKo0LzYrShqc4Bll13L4JcS_Um39rXtIBM0SLUSVj7vU_4l2ECmp87uzOlfMQnrtqzu
      - key: PAYPAL_MODE
        value: sandbox
      - key: FRONTEND_URL
        value: https://shridhar-frontend.onrender.com

  # Frontend
  - type: static
    name: shridhar-frontend
    runtime: node
    buildCommand: "cd frontend && npm install && npm run build"
    publishPath: "frontend/dist"
    envVars:
      - key: VITE_API_URL
        value: https://shridhar-backend.onrender.com
