# Generated by Django 6.0.3 on 2026-03-03 17:52

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('address_snapshot', models.JSONField(blank=True, help_text='Saved address JSON at order time', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('convenience_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('cod', 'Cash on Delivery'), ('upi', 'UPI')], default='cod', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('paypal_order_id', models.CharField(blank=True, help_text='PayPal order ID for capture/refund', max_length=100)),
                ('paypal_capture_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('confirmed', '✅ Confirmed'), ('processing', '🔧 Processing'), ('shipped', '🚚 Shipped'), ('delivered', '📦 Delivered'), ('cancelled', '❌ Cancelled'), ('refunded', '💸 Refunded')], default='pending', max_length=20)),
                ('customer_notes', models.TextField(blank=True, help_text="Customer's delivery instructions")),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes (not shown to customer)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Snapshot of product name at order time', max_length=255)),
                ('product_image_url', models.URLField(blank=True, help_text='Snapshot of product image URL')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit at order time', max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='MRP at order time', max_digits=10)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='CGST% at order time', max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=2.5, help_text='SGST% at order time', max_digits=5)),
            ],
            options={
                'verbose_name': 'Order Item',
            },
        ),
    ]
