# Generated by Django 6.0.3 on 2026-03-03 17:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon for category pill tab', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower = appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=50, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='Shown on product card', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Full HTML description')),
                ('ingredients', models.TextField(blank=True)),
                ('nutritional_info', models.JSONField(blank=True, help_text='JSON: {calories: 120, protein: 2g, ...}', null=True)),
                ('allergens', models.CharField(blank=True, help_text='e.g. Contains: Peanuts, Wheat', max_length=255)),
                ('shelf_life', models.CharField(blank=True, help_text='e.g. 6 months from manufacture date', max_length=100)),
                ('quantity_unit', models.CharField(default='piece', help_text='g, kg, ml, L, piece, pack', max_length=30)),
                ('weight', models.CharField(blank=True, help_text='e.g. 200g, 500ml', max_length=50)),
                ('pack_size', models.CharField(blank=True, help_text='e.g. Pack of 5, Box of 12', max_length=50)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='CGST percentage (default 5%)', max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=2.5, help_text='SGST percentage (default 2.5%)', max_digits=5)),
                ('stock', models.PositiveIntegerField(default=100)),
                ('max_per_order', models.PositiveIntegerField(default=10, help_text='Maximum units a customer can order in one transaction. Admin-controllable.')),
                ('is_available', models.BooleanField(default=True, help_text='Admin can toggle to hide product.')),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Shown in featured section on homepage')),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_veg', models.BooleanField(default=True, help_text='Veg/Non-veg indicator (green/red dot)')),
                ('country_of_origin', models.CharField(default='India', max_length=100)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='0 = primary/thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', 'is_featured'], name='products_pr_is_avai_f9ec00_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
    ]
