# Generated by Django 5.2.4 on 2026-03-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text="JSON: {'Size': ['200g', '500g'], 'Flavor': ['Spicy', 'Mild']}"),
        ),
        migrations.AddField(
            model_name='product',
            name='original_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
